# Generated by Django 6.0.2 on 2026-03-09 00:46

import django.utils.timezone
import toolbox.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('bug', 'Bug反馈'), ('feature', '功能建议'), ('other', '其他意见')], default='other', max_length=20, verbose_name='反馈类型')),
                ('tool_name', models.CharField(blank=True, default='', max_length=100, verbose_name='相关工具')),
                ('title', models.CharField(max_length=100, verbose_name='反馈标题')),
                ('content', models.TextField(max_length=2000, verbose_name='详细描述')),
                ('contact', models.CharField(blank=True, default='', max_length=200, verbose_name='联系方式')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=toolbox.models.feedback_image_upload_path, verbose_name='图片1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=toolbox.models.feedback_image_upload_path, verbose_name='图片2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to=toolbox.models.feedback_image_upload_path, verbose_name='图片3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to=toolbox.models.feedback_image_upload_path, verbose_name='图片4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to=toolbox.models.feedback_image_upload_path, verbose_name='图片5')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='用户代理')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '问题反馈',
                'verbose_name_plural': '问题反馈',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=60, verbose_name='标题')),
                ('category', models.CharField(default='unclassified', max_length=60, verbose_name='分类')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('tags', models.JSONField(verbose_name='标签')),
                ('url', models.CharField(max_length=60, verbose_name='url地址')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
            ],
        ),
    ]
